<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-40CLLRO" failures="1" tests="5" name="Personal loan" time="0.026" errors="0" timestamp="2021-04-19T11:04:47 CEST">
  <testcase classname="test.Day1" name="demo" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day1.demo(Day1.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase classname="test.Day2" name="plan" time="0.001"/>
  <testcase classname="test.Day4" name="loginAPIHomeLoan" time="0.0"/>
  <testcase classname="test.Day4" name="mobileLoginHomeLoan" time="0.001"/>
  <testcase classname="test.Day4" name="webLoginHomeLoan" time="0.0"/>
  <testcase classname="test.Day1" name="demo2" time="0.0">
    <ignored/>
  </testcase> <!-- demo2 -->
</testsuite> <!-- Personal loan -->
